# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DRM_ACCEL_APOLLO_HEXAGON) += apollo-hexagon-drm.o

apollo-hexagon-drm-y := apollo-hexagon.o
apollo-hexagon-drm-$(CONFIG_DRM_ACCEL_APOLLO_HEXAGON_SELFTEST) += \
	apollo-hexagon-selftest.o
